### ISSUE TITLE
I try flutter run get this error pls help 

### ISSUE THREAD

**Issue by nvcken** [tensor-programming/Flutter-Physics-Animations#1]
```
Starting Xcode build...
 ├─Assembling Flutter resources...             5.4s
 └─Compiling, linking and signing...          22.6s
Xcode build done                                     33.5s
Syncing files to device iPhone X...
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building MyApp(dirty):
Attempted to use type 'ThemeData' as a function. Since types do not define a method 'call', this is
not possible. Did you intend to call the ThemeData constructor and forget the 'new' operator?
Receiver: ThemeData
Tried calling: ThemeData(primaryColor: Instance of 'MaterialColor')

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      MyApp.build (/Users/cuongnv/thing/flutter-apps/Flutter-Physics-Animations/lib/main.dart:14:23)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
#10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
#11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
#13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
#14     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
#15     runApp (package:flutter/src/widgets/binding.dart:699:7)
#16     main (/Users/cuongnv/thing/flutter-apps/Flutter-Physics-Animations/lib/main.dart:7:16)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
════════════════════════════════════════════════════════════════════════════════════════════════════```

**Comment by braulio94** [comment]
@nvcken  My first guess is that you're not making use of `Dart 2`, read [README.md](https://github.com/tensor-programming/Flutter-Physics-Animations#to-build-this-application-you-will-need-the-latest-version-of-the-flutter-preview-build-and-dart-20-sdk-for-more-information-click-here) for instructions on how to setup `Dart 2`. Or you could add the `new` key word whereever it's needed.

**Comment by nvcken** [comment]
It works, thanks
